version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./project/db
    ports:
        - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    command: gunicorn -b 0.0.0.0:5000 django_react.wsgi:application
    build: ./
    volumes:
      - ./django_react:/usr/src/app/django_react
      - ./client:/usr/src/app/client
    ports:
      - 5000:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build: ./client/
    # build:
      # context: https://github.com/realpython/flask-microservices-client.git
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=0.0.0.0
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  nginx:
    container_name: nginx
    build: ./web-server/nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - web-service
