version: '2.1'

services:

  database:
    container_name: database
    build: ./database
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=users_dev
      - POSTGRES_PORT=5432
    healthcheck:
      test: exit 0

  backend:
    # prest
    container_name: backend
    build: ./backend
    environment:
        - PREST_DEBUG=false # so that jwt in prest works :D
        - PREST_CONF=./config.toml
    expose:
      - "3000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  frontend:
    # react
    container_name: frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
      # - REACT_APP_USERS_SERVICE_URL=http://localhost:1234/api/users_dev/public
    expose:
      - "5000"

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "1234:1234"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    links:
      - frontend
      - backend
