version: '2.1'

services:

  database:
    build: ./database
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=recruitment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=not_secret_at_all
    healthcheck:
      test: exit 0

  rest:
    build: ./rest
    volumes:
      - ./rest/config.toml:/srv/config.toml
    expose:
      - "3000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "1234:1234"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      rest:
        condition: service_started
    links:
      - rest
