version: '2.1'

services:

  database:
    build: ./database
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=recruitment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=not_secret_at_all
    healthcheck:
      test: exit 0

