version: '3'

services:

  elm:
    build: services/elm
    image: img-elm
    environment:
      - HOME=/tmp
    volumes:
      - .:/code
    working_dir: /code
    user: "1000:"
    ports:
      - 8000:8000


  db:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=sa
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_PORT=5432
      - JWT_SECRET=not_secret_at_all
    volumes:
      - ./services/db/extension/pgjwt.control:/usr/local/share/postgresql/extension/pgjwt.control
      - ./services/db/extension/pgjwt--0.0.1.sql:/usr/local/share/postgresql/extension/pgjwt--0.0.1.sql
      - ./services/db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: exit 0

  postgrest:
    build: services/postgrest
    image: img-postgrest
    volumes:
      - ./services/postgrest/config.toml:/srv/config.toml
    expose:
      - 3000
    depends_on:
      - db
    links:
      - db
    command: /srv/postgrest /srv/config.toml

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 1234:1234
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgrest
    links:
      - postgrest
