version: '2.1'

services:

  database:
    image: postgres:latest
    # container_name: database
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DATABASE=sa
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: exit 0

  prest:
    # image: prest
    # container_name: prest
    build: ./prest
    volumes:
      - ./prest/config.toml:/srv/config.toml
    environment:
        - PREST_DEBUG=false  # Enables JWT
        - PREST_CONF=/srv/config.toml
    expose:
      - 3000
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  react:
    # react
    # image: img-react
    # container_name: react
    build: ./react
    environment:
      - NODE_ENV=development
    expose:
      - 5000

  flask:
    # image: img-flask
    # container_name: flask
    build: ./flask
    ports:
      - 4000
    # depends_on:
    #   prest:
    #     condition: service_started

  nginx:
    image: nginx:alpine
    # container_name: nginx
    restart: always
    ports:
      - 80:1234
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      prest:
        condition: service_started
      react:
        condition: service_started
    links:
      - react
      - prest
      - flask
